channels:
  - conda-forge
  - defaults
dependencies:
  - altair=4.1.0
  - anyio=2.2.0
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.3.0
  - brotlipy=0.7.0
  - ca-certificates=2021.5.25
  - certifi=2021.5.30
  - cffi=1.14.5
  - chardet=4.0.0
  - cryptography=3.4.7
  - cycler=0.10.0
  - decorator=5.0.9
  - defusedxml=0.7.1
  - entrypoints=0.3
  - freetype=2.10.4
  - idna=2.10
  - importlib-metadata=3.10.0
  - importlib_metadata=3.10.0
  - intel-openmp=2021.2.0
  - ipykernel=5.3.4
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - jedi=0.17.2
  - jinja2=3.0.0
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter-packaging=0.7.12
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyter_server=1.4.1
  - jupyterlab=3.0.14
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.4.0
  - kiwisolver=1.3.1
  - lcms2=2.12
  - libcxx=10.0.0
  - libffi=3.3
  - libgfortran>3.0.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.2.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mistune=0.8.4
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - notebook=6.4.0
  - numpy=1.20.2
  - numpy-base=1.20.2
  - olefile=0.46
  - openssl=1.1.1k
  - packaging=20.9
  - pandas=1.2.4
  - pandoc=2.12
  - pandocfilters=1.4.3
  - parso=0.7.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.1.2
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.17
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pygments=2.9.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.9.5
  - python-dateutil=2.8.1
  - python_abi=3.9
  - pytz=2021.1
  - pyzmq=20.0.0
  - readline=8.1
  - requests=2.25.1
  - scipy=1.6.2
  - send2trash=1.5.0
  - setuptools=52.0.0
  - six=1.16.0
  - sniffio=1.2.0
  - sqlite=3.35.4
  - terminado=0.9.4
  - testpath=0.4.4
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - traitlets=5.0.5
  - tzdata=2020f
  - urllib3=1.26.4
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
